### ISSUE TITLE
Compiled sucessfully in Windows 10 Python 3.11 but CreateProcess fails (call to dispread to measure) 

### ISSUE THREAD

**Issue by VgerTest** [eoyilmaz/displaycal-py3#367] opened 2024-05-21 19:43 UTC
```shell
 Traceback (most recent call last):                                           
  File "D:\src\otros\displaycal-py3.py311\DisplayCAL\worker.py", line 7082,  
 in exec_cmd                                                                  
     self.subprocess = wexpect.spawn(                                         
                       ^^^^^^^^^^^^^^                                         
   File "D:\src\otros\displaycal-py3.py311\DisplayCAL\wexpect.py", line 328,  
 in spawn                                                                     
     return spawn_windows(                                                    
            ^^^^^^^^^^^^^^                                                    
   File "D:\src\otros\displaycal-py3.py311\DisplayCAL\wexpect.py", line 1775, 
 in __init__                                                                  
     self._spawn(command, args)                                               
   File "D:\src\otros\displaycal-py3.py311\DisplayCAL\wexpect.py", line 1848, 
 in _spawn                                                                    
     self.child_fd = self.wtty.spawn(self.command, self.args, self.env)       
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
   File "D:\src\otros\displaycal-py3.py311\DisplayCAL\wexpect.py", line 2073, 
 in spawn                                                                     
     self.startChild(args, env)                                               
   File "D:\src\otros\displaycal-py3.py311\DisplayCAL\wexpect.py", line 2174, 
 in startChild                                                                
     self.__oproc, _, self.conpid, self.__otid = CreateProcess(               
                                                 ^^^^^^^^^^^^^^               
 TypeError: Objects of type 'bytes' can not be converted to Unicode.         
```

It does not like this:
```
        self.__oproc, _, self.conpid, self.__otid = CreateProcess(
            None, commandLine, None, None, False, CREATE_NEW_CONSOLE, env, self.cwd, si
        )
```

**Comment by wisdomk** [comment] 2024-05-22 09:07
same issue here ... I am very frustrated, I've spent like 5 hours trying to make this thing work on Windows with no avail.
On Ubuntu and Mac it works like a charm though.

**Comment by eoyilmaz** [comment] 2024-06-01 12:02
okay I'll look into this shortly

**Comment by eoyilmaz** [comment] 2024-06-02 12:04
Fixed this, but there are other problems preventing DisplayCAL to run properly... working on it.

**Comment by eoyilmaz** [comment] 2024-06-02 12:28
I think we need to use the PIP version of wexpect now... Our version is old and not working properly...

**Comment by eoyilmaz** [comment] 2024-06-05 00:53
Still working on this with no avail...

The main problem is that DisplayCAL cannot read from the `stdout` of the child process that is spawned through `DisplayCAL.wexpect` module. I tried using the `Wexpect` module from PyPI, hopefully the interface has not been changed and DisplayCAL was able to use it to spawn processes. But it is didn't solve the problem. Then I tried using different Python versions, i.e 3.9, 3.10, 3.11, 3.12, in none of them the Wexpect is working properly. Tried using `utf-8` instead `cp1252` (which was the default) for the code page, not working... Tried using different ArgyllCMS versions from 3.02, 3.1.0 to 3.2.0, same error.

I believe in the past with an update called "Windows Creators Update" the behaviour of the `stdout` has changed, still trying to understand why it is not working...

**Comment by eoyilmaz** [comment] 2024-06-05 01:05
As always as soon as I sent a progress message here I solve something 😄 

Apparently setting the "PYTHONLEGACYWINDOWSSTDIO" environment variable to anything reverts the behaviour change and I can now start the measurement and finally was able to skip the first couple of colour patches. But unfortunatelly, it is not progresssing any further...

**Comment by eoyilmaz** [comment] 2024-06-05 11:36
Finally, I managed to make it work...

Obviously we had an encoding issue under Windows and one another issue was the `DisplayCAL.worker._safe_send()` was trying to encode whatever it was trying to send to the subprocess to `bytes` and it was not working properlly under Windows. Now all seems to be fixed and I'm currently doing a profiling and it is working fine 👍

aaand profiling is done... but it seems that there are other issues and no profile has been created... let's fix them too.

**Comment by eoyilmaz** [comment] 2024-06-05 14:10
Okay fixed a couple more problems and I was able to finish my first calibration and profile generation under Windows 10 🎆

**Comment by eoyilmaz** [comment] 2024-06-05 21:36
Anyone who wants to try DisplayCAL under Windows, I updated the installation instructions here: [How To Install (Windows)](https://github.com/eoyilmaz/displaycal-py3/tree/367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure?tab=readme-ov-file#how-to-install-windows)

Please try and report back.

**Comment by eoyilmaz** [comment] 2024-06-06 00:21
Fixed the `codepage` being `cp1252` vs `utf-8` issue without relying on the legacy `stdio` trick (`PYTHONLEGACYWINDOWSSTDIO` env var). So, Python 3.9, 3.10 and 3.11 are all working properly. Unfortunatelly some packages are not available for Python 3.12 so we are not currently supporting it.

I want to merge the changes to `develop` branch. If anyone finds out any issues we can handle them in new issue tickets.

**Comment by johnloopi** [comment] 2024-06-06 11:08
> Anyone who wants to try DisplayCAL under Windows, I updated the installation instructions here: [How To Install (Windows)](https://github.com/eoyilmaz/displaycal-py3/tree/367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure?tab=readme-ov-file#how-to-install-windows)
> 
> Please try and report back.

I'll test it on my Windows 10 and 11 pcs later this evening and report back to you. :)

**Comment by VgerTest** [comment] 2024-06-06 17:33
"pip install displaycal"
Failed due to an absolute path /Users/eoyilmaz

Manually build without venv on a clean Py3.9 as in screenshots:
pip install -r requirements.txt
python -m build
pip install dist\DisplayCAL-3.9.12-cp39-cp39-win_amd64.whl
All OK

Running with Argyll 32 (64 has some issues about non accesing id3 device, but those where in DisplayCAL py2.7)
-minor issues with CCSS names
-console report uncalibrated/calibrated (dispcal -R/-r) OK
-calibration OK
-profiling crashes : 
DisplayCAL: Starting interaction with subprocess
dispread: Error - CGATS file read error : Unable to open file 'Measurement.ti1' for reading
DisplayCAL: Reached EOF (OK)
dispread exitcode: 1

-measurement report crashes
DisplayCAL: Starting interaction with subprocess
dispread: Error - CGATS file read error : Unable to open file 'Measurement.ti1' for reading
DisplayCAL: Reached EOF (OK)
dispread exitcode: 1

I tried to manually select ti1 file but same result.


Also on startup:
writing to lock file: port: 15411
**No module named 'comtypes.gen'
Error - could not import WMI: No module named 'wmi'**
Comenzando...
Audio module: wx 4.2.1
Inicializando GUI...

**Comment by johnloopi** [comment] 2024-06-06 17:33
Since the version on PyPi is still version 3.9.12, I'm met with the same error as @opopnever was here https://github.com/eoyilmaz/displaycal-py3/issues/349 and @dkflint723 was here: https://github.com/eoyilmaz/displaycal-py3/issues/334

```
        File "C:\Users\MyUser\AppData\Local\Temp\pip-build-env-xlh9khju\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 132, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/Users/eoyilmaz/Documents/development/displaycal-py3/CHANGES.html' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\Users\MyUser>

```
I therefore tried building it myself, which I'm not very good at it seems, by doing this:
I downloaded the newest test-branch, unzipped it, cmd'd into the unzipped folder and ran the commands from Alex Hawk's attachment file here https://hub.displaycal.net/forums/topic/displaycal-is-dead-time-to-move-on-what-alternative-you-choosed/page/5/#post-141305

For some reason it gives me the files "displaycal-0.0.0.tar.gz" and "DisplayCAL-0.0.0-cp311-cp311-win_amd64.whl" instead of "displaycal-3.9.12.tar.gz" and "DisplayCAL-3.9.12-cp310-cp310-win_amd64.whl" and when I open it with command "python -m DisplayCAL" I am met with a message to update to DisplayCAL 3.8.9.3, since my version thinks it's 0.

Could it be because I'm doing this in a VM and not a "real" computer? I figured it would be easier to roll back any changes with snapshots in a VM if something went wrong or I should change something quickly.

**Comment by eoyilmaz** [comment] 2024-06-06 17:38
Ah sorry, I was completely confused when I written my previous message. The install instructions are explaining what needs to be done in the future, when we upload the current version to PyPI. The current version in PyPI is expected to fail.

What you can do is to use the following tarbal and install through that: [displaycal-3.9.12-202406061835.tar.gz](https://github.com/user-attachments/files/15667362/displaycal-3.9.12-202406061835.tar.gz)

An run the following:

```shell
  pip install displaycal-3.9.12-202406061835.tar.gz
```

**Comment by johnloopi** [comment] 2024-06-06 18:17
> Ah sorry, I was completely confused when I written my previous message. The install instructions are explaining what needs to be done in the future, when we upload the current version to PyPI. The current version in PyPI is expected to fail.
> 
> What you can do is to use the following tarbal and install through that: [displaycal-3.9.12-202406061835.tar.gz](https://github.com/user-attachments/files/15667362/displaycal-3.9.12-202406061835.tar.gz)
> 
> An run the following:
> 
> ```shell
>   pip install displaycal-3.9.12-202406061835.tar.gz
> ```

I am getting some warnings like:
`WARNING: The script clear_comtypes_cache.exe is installed in 'C:\Users\MyUser\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.`
and:
`No module named 'comtypes.gen'`
`Error - could not import WMI: No module named 'wmi'`

But it starts up, and installs ArgyllCMS 3.2.0 without any issues. Will let my meters warm up for a bit, EFI ES-2000 and X-Rite i1 Display Pro Plus, and then I will test ICC calibration and .Cube.

Anything else you want me to test?

**Comment by eoyilmaz** [comment] 2024-06-06 19:02
> WARNING: The script clear_comtypes_cache.exe is installed in 'C:\Users\MyUser\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.

I think when you installed Python 3.11 you didn't select "Add Python 3.11 to PATH", just run the Python installer again, it will show a similar option. 

> No module named 'comtypes.gen'
> Error - could not import WMI: No module named 'wmi'

These are not required, they were neded for older versions of Windows (XP and 2000), ignore them

**Comment by johnloopi** [comment] 2024-06-06 19:53
> > WARNING: The script clear_comtypes_cache.exe is installed in 'C:\Users\MyUser\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
> 
> I think when you installed Python 3.11 you didn't select "Add Python 3.11 to PATH", just run the Python installer again, it will show a similar option.
>
I did select "Add python.exe to PATH", but I also clicked "Customize installation" and "Install for all users" out of old habits. Uninstalling Python 3.11, reinstalling it, and just clicking "Install now" without customizing further worked to get rid of that error.
> 
> > No module named 'comtypes.gen'
> > Error - could not import WMI: No module named 'wmi'
> 
> These are not required, they were neded for older versions of Windows (XP and 2000), ignore them.
> 
That's good to know.
> > Anything else you want me to test?
> 
> Just calibration and profiling is enough for now. But, of course, test as many things as possible. But I would most probably prefer to handle them as individual tickets.
>
Got it, if I encounter any issues I'll create a new ticket(s) for them.

**Comment by eoyilmaz** [comment] 2024-06-07 21:53
I added a [Manual Installation (Windows)](https://github.com/eoyilmaz/displaycal-py3/tree/367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure?tab=readme-ov-file#manual-setup-windows) section to the README, that describes how to build and install the development version under Windows. It is better to follow that instead of the "How To Install (Windows)" section.

**Comment by berryboy2012** [comment] 2024-06-10 06:38
> Still working on this with no avail...
> 
> The main problem is that DisplayCAL cannot read from the `stdout` of the child process that is spawned through `DisplayCAL.wexpect` module. I tried using the `Wexpect` module from PyPI, hopefully the interface has not been changed and DisplayCAL was able to use it to spawn processes. But it is didn't solve the problem. Then I tried using different Python versions, i.e 3.9, 3.10, 3.11, 3.12, in none of them the Wexpect is working properly. Tried using `utf-8` instead `cp1252` (which was the default) for the code page, not working... Tried using different ArgyllCMS versions from 3.02, 3.1.0 to 3.2.0, same error.
> 
> I believe in the past with an update called "Windows Creators Update" the behaviour of the `stdout` has changed, still trying to understand why it is not working...

Possible related issue https://github.com/raczben/wexpect/issues/26 with proposed fix at https://github.com/raczben/wexpect/commit/850eece43bb21b46c78053a078d76cb3cce92d3e .

**Comment by eoyilmaz** [comment] 2024-06-10 07:24
@berryboy2012 ah yeah that's a good idea 👍

**Comment by alex-mirkin** [comment] 2024-06-22 11:40
Installed Python 3.11 using scoop.
Build and installed successfully, but got this when tried to run:
```
ModuleNotFoundError: No module named 'win32file'
```

Solved with `python -m pip install pywin32`.
Maybe it wasn't installed because of scoop?

**Comment by eoyilmaz** [comment] 2024-06-22 12:21
@alex-mirkin did you follow [Manual Setup (Windows)](https://github.com/eoyilmaz/displaycal-py3/tree/367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure?tab=readme-ov-file#manual-setup-windows) and installed it from the correct branch? If you used any other version it will not work on Windows properly.

**Comment by alex-mirkin** [comment] 2024-06-22 17:16
> @alex-mirkin did you follow [Manual Setup (Windows)](https://github.com/eoyilmaz/displaycal-py3/tree/367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure?tab=readme-ov-file#manual-setup-windows) and installed it from the correct branch? If you used any other version it will not work on Windows properly.

@eoyilmaz I've tested again using fresh Windows 11 VM install.
Followed the [Manual Setup (Windows)](https://github.com/eoyilmaz/displaycal-py3/tree/367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure?tab=readme-ov-file#manual-setup-windows) and installed it from `develop` branch.
This time used the official python 3.11 installer instead of using `scoop` to install python.
Still got the `ModuleNotFoundError: No module named 'win32file'` error.
adding this to requirements.txt solves the issue for new installs:
```
pywin32; sys_platform=='win32'
```

**Comment by eoyilmaz** [comment] 2024-06-22 17:24
Yeah don't use the develop branch it is the wrong one use '367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure'

**Comment by alex-mirkin** [comment] 2024-06-22 17:54
Ooh totally missed that part :)
Thanks!

**Comment by Rickyneer** [comment] 2024-07-06 11:50
Hello all,

I noticed that any paths with spaces will not create a calibration file properly anymore (E.g. file called "hello world" would have it's .cal file be generated as "hello.cal".

I do notice the quote_args function was imported, but it isn't used in the prepare_dispcal function.

The appropriate change would be at https://github.com/eoyilmaz/displaycal-py3/blob/367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure/DisplayCAL/worker.py#L13579

Where `return cmd, args` should become `return cmd, quote_args(args)`

Can this be confirmed and are there any other command lines opened where this doesn't happen yet?

Thanks!

**Comment by Rickyneer** [comment] 2024-07-06 12:01
> Hello all,
> 
> I noticed that any paths with spaces will not create a calibration file properly anymore (E.g. file called "hello world" would have it's .cal file be generated as "hello.cal".
> 
> I do notice the quote_args function was imported, but it isn't used in the prepare_dispcal function.
> 
> The appropriate change would be at https://github.com/eoyilmaz/displaycal-py3/blob/367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure/DisplayCAL/worker.py#L13579
> 
> Where `return cmd, args` should become `return cmd, quote_args(args)`
> 
> Can this be confirmed and are there any other command lines opened where this doesn't happen yet?
> 
> Thanks!

Actually, is it maybe better to do this in the exec_cmd function?

**Comment by MCPO-Spartan-117** [comment] 2024-09-10 01:20
Verification fails with `Error - CGATs file read error: Unable to open 'Measurement.ti1' for reading`.
Like what @Rickyneer said, spaces without the change fails on profiling.

**Comment by eoyilmaz** [comment] 2024-09-22 18:27
> Verification fails with `Error - CGATs file read error: Unable to open 'Measurement.ti1' for reading`. Like what @Rickyneer said, spaces without the change fails on profiling.

I believe, should be made Windows safe. But I would like to handle this in a different ticket and close this one now, as we already have a PR for this ticket and ready to merge.

**Comment by eoyilmaz** [comment] 2024-09-23 16:47
I merged @AstralStorm 's changes, and introduced a couple more Windows related fixes and I think we should merge this now. But please test this branch (by using the instractions here: [Manual Setup (Windows)](https://github.com/eoyilmaz/displaycal-py3/tree/367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure?tab=readme-ov-file#manual-setup-windows) )

**Comment by eoyilmaz** [comment] 2024-10-09 10:09
> Verification fails with `Error - CGATs file read error: Unable to open 'Measurement.ti1' for reading`. Like what @Rickyneer said, spaces without the change fails on profiling.

Fixed with b8a507bdcb7d716be68d04800f95f955d101a2a3

**Closed** 2024-10-10 10:23 UTC

**Comment by Ivanmatthew** [comment] 2024-10-10 11:49
Thank you for your efforts @eoyilmaz 
Cheers! 🥂

**Comment by Headcrabed** [comment] 2024-10-10 19:12
@eoyilmaz Seems this new version has a encoding problem on my Simplified Chinese Windows 11. You might need to force text encoding somewhere:
```
D:\Tools\Argyll_V3.2.0\bin\dispcal.exe -v2 -d1 -c1 -yl                       │
│ -P0.787200832466181,0.40897755610972564,1.4941451990632322 -H -Ibw -qm       │
│ -w0.3127,0.329 -b{luminance} -gs -f1.0 -A4.0 ULTRAGEAR #1 2024-10-11 03-04   │
│ 120cdm² 0.3127x 0.329y sRGB M-S XYZLUT+MTX                                   │
│ Traceback (most recent call last):                                           │
│   File "C:\Program Files\Python311\Lib\site-packages\DisplayCAL\worker.py",  │
│ line 7091, in exec_cmd                                                       │
│     self.subprocess = wexpect.spawn(                                         │
│                       ^^^^^^^^^^^^^^                                         │
│   File "C:\Program Files\Python311\Lib\site-packages\DisplayCAL\wexpect.py", │
│ line 372, in spawn                                                           │
│     log("Spawning {}".format(join_args([command] + args)))                   │
│   File "C:\Program Files\Python311\Lib\site-packages\DisplayCAL\wexpect.py", │
│ line 2992, in log                                                            │
│     fout.write(                                                              │
│ UnicodeEncodeError: 'gbk' codec can't encode character '\xb2' in position    │
│ 240: illegal multibyte sequence
```

**Comment by eoyilmaz** [comment] 2024-10-11 06:26
@Headcrabed let's make a new issue 👍
