### ISSUE TITLE
PyPI installation: ModuleNotFoundError: No module named 'win32file'

### ISSUE THREAD

**Issue by fishcu** [eoyilmaz/displaycal-py3#201] opened 2022-11-09 20:49 UTC
The above error occurs when trying to install DisplayCAL through PyPI on Windows 10, version 22H2. I am using Miniconda to install and manage different Python versions. The current default version in the base environment is Python 3.9.12.

pywin32 is already installed. So this error is puzzling to me. I have also tried this approach to re-install it: https://community.intel.com/t5/Intel-Distribution-for-Python/ModuleNotFoundError-No-module-named-win32file/m-p/1136507
However, it did not help.

I then tried to set up a fresh environment. This used Python 3.10.6. However, it did not help. Again, I also tried to additionally install pywin32.

I then tried to additionally install all the dependencies listed in requirements.txt. This gave me an error when trying to install `dbus-python` related to CMake. I installed CMake 3.25.0. However, more errors showed up at that point -- it requires Ninja and probably a compiler installed with Visual Studio. At that point, I gave up trying to install the requirements.

Any help for an easier installation in Windows would be appreciated.

**Comment by fishcu** [comment] 2022-11-09 20:51
Here's a full log.

[full_error_log.txt](https://github.com/eoyilmaz/displaycal-py3/files/9974995/full_error_log.txt)

**Comment by p5k369** [comment] 2022-11-10 11:03
Hey @fishcu, even if you manage to install all dependencies, DisplayCal won't run on win10 without manual tinkering and even than you won't be able to perform any measurements at the moment.
This is basically a duplicate of #34

**Comment by eoyilmaz** [comment] 2022-11-20 23:02
Unfortunately, I'm very much concentrated on fixing bugs in Linux (and now MacOS). The DisplayCAL 3.8.9.3 version can still be run in Windows and for now we are not adding new features but just making it work on Linux and MacOS machines.

**Comment by eoyilmaz** [comment] 2024-03-19 22:42
3.9.12 is now released try using it as it improves Windows compatibility.

**Comment by eoyilmaz** [comment] 2024-09-24 11:36
#367 is addressed most of the issues with Windows. So closing this one,

**Closed by eoyilmaz** 2024-09-24 11:36 UTC
Labels: duplicate
