### ISSUE TITLE
python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by saltarob** [eoyilmaz/displaycal-py3#242] opened 2023-03-17 13:07 UTC
Hi the `pip install -r requirements.txt` command gives me following error on macOS 13.2.1. Is there any solution? Thank you.

```
Collecting wxPython>=4.1.1
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/z8/pk5dbj2x1_xd67mxx0c_v3sc0000gn/T/pip-install-ypiazdlx/wxpython_02899c28bb3c46a6b88fda255e996ae3/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/private/var/folders/z8/pk5dbj2x1_xd67mxx0c_v3sc0000gn/T/pip-install-ypiazdlx/wxpython_02899c28bb3c46a6b88fda255e996ae3/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by HacDan** [comment] 2023-03-17 14:24
If you manually install `attrdict` with `pip` this goes away. 

Ex:
```sh
pip install attrdict
```
I'm guessing you'll run into another error after this, but that will resolve this issue. It should be added to `requirements.txt`

**Comment by p5k369** [comment] 2023-03-17 14:33
Hey @saltarob, you can:
- use the develop branch
- limit wxpython to 4.1.1
- or install attrdict manually before installing wxpython 4.2.0 via `pip install attrdict3`

@HacDan note that installing _attrdict_ won't fix this issue

this is a duplicate of #235

**Comment by HacDan** [comment] 2023-03-17 14:40
@p5k369 It did about 5 minutes before I posted this. Not sure how else to explain it. Mind you, this is on an Ubuntu system, maybe that's the difference?

**Comment by saltarob** [comment] 2023-03-17 14:53
Thank you. I did `pip install attrdict3`. But now I got following error: 

```
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... done
  Created wheel for wxPython: filename=wxPython-4.2.0-cp311-cp311-macosx_13_0_x86_64.whl size=24787860 sha256=304ff6837315bb4bb952e6acda1ff9337087c00130a72b88d15893892e37fafe
  Stored in directory: /Users/abdulhadi/Library/Caches/pip/wheels/47/fd/13/25e893cf569416a9322b9c5d7efc0f82e8267efba2ecd950c5
Successfully built wxPython
Installing collected packages: Send2Trash, ifaddr, zeroconf, wxPython, urllib3, pyproject_hooks, protobuf, idna, distro, charset-normalizer, certifi, requests, build, casttube, PyChromecast
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/LICENSE'
Consider using the `--user` option or check the permissions.
```

**Comment by saltarob** [comment] 2023-03-17 14:58
Oh, I oversaw that the virtual environment activation command failed. Did I mess up the system python now?

**Comment by saltarob** [comment] 2023-03-17 15:12
How do I get 3.10 into the virtual environment?

**Comment by saltarob** [comment] 2023-03-17 15:32
Okay I made a new virtual environment with `python3.10 -m venv venv310`. Starting again from scratch.

**Comment by saltarob** [comment] 2023-03-18 10:03
How can I make it work now?

**Comment by p5k369** [comment] 2023-03-20 17:42
Hey @saltarob, from the few lines it is not clear whether everything is as it should be. If I had to guess, I would say you've build a python wheel in a virtual environment and try to install it into your system, but the naming is not correct (it could be an issue with '-' and ' _', I am not on macOS and cannot replicate that errror) or the file does not exist.

**Comment by saltarob** [comment] 2023-03-20 19:37
Hi @p5k369, thank you for your answer. I copied the whole build process in a text file. There are some warnings but at the end it said it was successfully build and the file exists. Maybe I should try to python 3.10 in the other venv where the installation worked...

[Build&Install.pdf](https://github.com/eoyilmaz/displaycal-py3/files/11022364/Build.Install.pdf)

**Comment by p5k369** [comment] 2023-03-20 19:57
You have 2 wheels in the same directory, one was build for python-3.10 and one for python-3.11.
If you tell pip to install via wildcard it will install all wheels which match your pattern, so both of them. That won't work. Tell pip exactly what to install or remove unnecessary wheels from the directory.

**Comment by saltarob** [comment] 2023-03-20 20:06
Great. Thank you so much. It worked and the DisplayCAL GUI is open now. 😊

**Closed** 2023-04-29 15:12 UTC
Labels: duplicate
