### ISSUE TITLE
pip install of 3.9.11 fails on Fedora 38 with Python 3.11 - Unable to build wheels

### ISSUE THREAD

**Issue by brunkenj** [eoyilmaz/displaycal-py3#264] opened 2023-06-11 12:56 UTC
I'm seeing this on a system that is freshly upgraded from Fedora 36 to 38. This system has DisplayCAL 3.9.10 on it, and it was working under Fedora 36 (with Python 3.10).

I've pasted a snippet of the error output. A full copy of the pip output is attached.

Thanks -

```
Building wheels for collected packages: DisplayCAL
  Building wheel for DisplayCAL (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for DisplayCAL (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
<SNIP>
      desktopfile: /tmp/pip-install-_2sn1typ/displaycal_e98199d45c334eb3b66c241773e2dc83/DisplayCAL/../misc/displaycal-vrml-to-x3d-converter.desktop
      error: can't copy '/tmp/pip-install-_2sn1typ/displaycal_e98199d45c334eb3b66c241773e2dc83/DisplayCAL/../dist/net.displaycal.DisplayCAL.appdata.xml': doesn't exist or not a regular file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for DisplayCAL
Failed to build DisplayCAL
ERROR: Could not build wheels for DisplayCAL, which is required to install pyproject.toml-based projects
```

[pip_install.txt](https://github.com/eoyilmaz/displaycal-py3/files/11714638/pip_install.txt)

**Comment by mabachel** [comment] 2023-06-20 05:42
Confirmed.

Both methods of installing displaycal-py3 (from source and through pip) are failing on Fedora 38 because wheels cannot be build.

**Comment by mdilena** [comment] 2023-06-20 21:10
Hello!

This has happened to me last night when trying to pip install on both Python 3.8 and 3.9 on Ubuntu 20.04, same error message about building the wheel.

**Comment by mabachel** [comment] 2023-06-22 08:54
On develop branch I get another error:

```
Program python found: YES (/home/relentless/Playground/displaycal_venv/bin/python)
      Dependency dbus-1 found: YES 1.14.8 (cached)
      Configuring TestSuitePythonService.service using configuration
      Configuring tmp-session-bus.conf using configuration
      Program dbus-run-session found: YES (/usr/bin/dbus-run-session)
      
      ../../test/meson.build:98:15: ERROR: Python dependency not found
      
      A full log can be found at /tmp/pip-install-y0t13erd/dbus-python_537e6a900ebd4c1b8baa6dbc08adb00c/.mesonpy-unx38wef/build/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
(displaycal_venv) [relentless@machine displaycal-py3]$ cat /tmp/pip-install-y0t13erd/dbus-python_537e6a900ebd4c1b8baa6dbc08adb00c/.mesonpy-unx38wef/build/meson-logs/meson-log.txt
cat: /tmp/pip-install-y0t13erd/dbus-python_537e6a900ebd4c1b8baa6dbc08adb00c/.mesonpy-unx38wef/build/meson-logs/meson-log.txt: No such file or directory
(displaycal_venv) [relentless@machine displaycal-py3]$ 

```

**Comment by OldNick** [comment] 2023-06-26 12:01
It won't install on OpenSuse Tumbleweed either - I suspect the issue is probably the same - Python version is 3.11. Below the whole process as relayed in Konsole:

`:~> pip install displaycal
Defaulting to user installation because normal site-packages is not writeable
Collecting displaycal
  Using cached DisplayCAL-3.9.11.tar.gz (10.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: build in ./.local/lib/python3.11/site-packages (from displaycal) (0.10.0)
Requirement already satisfied: certifi in /usr/lib/python3.11/site-packages (from displaycal) (2023.5.7)
Requirement already satisfied: distro in /usr/lib/python3.11/site-packages (from displaycal) (1.8.0)
Requirement already satisfied: numpy in /usr/lib64/python3.11/site-packages (from displaycal) (1.24.2)
Requirement already satisfied: Pillow in ./.local/lib/python3.11/site-packages (from displaycal) (9.5.0)
Requirement already satisfied: PyChromecast in ./.local/lib/python3.11/site-packages (from displaycal) (13.0.7)
Requirement already satisfied: Send2Trash in /usr/lib/python3.11/site-packages (from displaycal) (1.8.0)
Requirement already satisfied: wxPython in /usr/lib64/python3.11/site-packages (from displaycal) (4.2.0)
Requirement already satisfied: zeroconf in ./.local/lib/python3.11/site-packages (from displaycal) (0.69.0)
Requirement already satisfied: dbus-python in ./.local/lib/python3.11/site-packages (from displaycal) (1.3.2)
Requirement already satisfied: packaging>=19.0 in ./.local/lib/python3.11/site-packages (from build->displaycal) (23.1)
Requirement already satisfied: pyproject_hooks in ./.local/lib/python3.11/site-packages (from build->displaycal) (1.0.0)
Requirement already satisfied: protobuf>=3.19.1 in ./.local/lib/python3.11/site-packages (from PyChromecast->displaycal) (4.23.3)
Requirement already satisfied: casttube>=0.2.0 in ./.local/lib/python3.11/site-packages (from PyChromecast->displaycal) (0.2.1)
Requirement already satisfied: ifaddr>=0.1.7 in ./.local/lib/python3.11/site-packages (from zeroconf->displaycal) (0.2.0)
Requirement already satisfied: six in /usr/lib/python3.11/site-packages (from wxPython->displaycal) (1.16.0)
Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (from casttube>=0.2.0->PyChromecast->displaycal) (2.31.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests->casttube>=0.2.0->PyChromecast->displaycal) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests->casttube>=0.2.0->PyChromecast->displaycal) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests->casttube>=0.2.0->PyChromecast->displaycal) (2.0.2)
Building wheels for collected packages: displaycal
  Building wheel for displaycal (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for displaycal (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      /tmp/pip-build-env-nyrqfg3w/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      DisplayCAL/RealDisplaySizeMM.c: In function ‘get_displays’:
      DisplayCAL/RealDisplaySizeMM.c:871:61: warning: pointer targets in passing argument 11 of ‘XRRGetOutputProperty’ differ in signedness [-Wpointer-sign]
        871 |                                     &ret_type, &ret_format, &ret_len, &ret_togo, &atomv) == Success
            |                                                             ^~~~~~~~
            |                                                             |
            |                                                             long int *
      In file included from DisplayCAL/RealDisplaySizeMM.c:33:
      /usr/include/X11/extensions/Xrandr.h:339:38: note: expected ‘long unsigned int *’ but argument is of type ‘long int *’
        339 |                       unsigned long *nitems, unsigned long *bytes_after,
            |                       ~~~~~~~~~~~~~~~^~~~~~
      DisplayCAL/RealDisplaySizeMM.c:871:71: warning: passing argument 12 of ‘XRRGetOutputProperty’ from incompatible pointer type [-Wincompatible-pointer-types]
        871 |                                     &ret_type, &ret_format, &ret_len, &ret_togo, &atomv) == Success
            |                                                                       ^~~~~~~~~
            |                                                                       |
            |                                                                       long unsigned int **
      /usr/include/X11/extensions/Xrandr.h:339:61: note: expected ‘long unsigned int *’ but argument is of type ‘long unsigned int **’
        339 |                       unsigned long *nitems, unsigned long *bytes_after,
            |                                              ~~~~~~~~~~~~~~~^~~~~~~~~~~
      DisplayCAL/RealDisplaySizeMM.c:1036:53: warning: pointer targets in passing argument 10 of ‘XGetWindowProperty’ differ in signedness [-Wpointer-sign]
       1036 |                             &ret_type, &ret_format, &ret_len, &ret_togo, &atomv) == Success
            |                                                     ^~~~~~~~
            |                                                     |
            |                                                     long int *
      In file included from DisplayCAL/RealDisplaySizeMM.c:27:
      /usr/include/X11/Xlib.h:2700:5: note: expected ‘long unsigned int *’ but argument is of type ‘long int *’
       2700 |     unsigned long*      /* nitems_return */,
            |     ^~~~~~~~~~~~~~
      DisplayCAL/RealDisplaySizeMM.c:1036:63: warning: pointer targets in passing argument 11 of ‘XGetWindowProperty’ differ in signedness [-Wpointer-sign]
       1036 |                             &ret_type, &ret_format, &ret_len, &ret_togo, &atomv) == Success
            |                                                               ^~~~~~~~~
            |                                                               |
            |                                                               long int *
      /usr/include/X11/Xlib.h:2701:5: note: expected ‘long unsigned int *’ but argument is of type ‘long int *’
       2701 |     unsigned long*      /* bytes_after_return */,
            |     ^~~~~~~~~~~~~~
      DisplayCAL/RealDisplaySizeMM.c: In function ‘enumerate_displays’:
      DisplayCAL/RealDisplaySizeMM.c:1364:56: warning: pointer targets in passing argument 1 of ‘PyBytes_FromStringAndSize’ differ in signedness [-Wpointer-sign]
       1364 |               (value = PyString_FromStringAndSize(dp[i]->edid, dp[i]->edid_len)) != NULL) {
            |                                                   ~~~~~^~~~~~
            |                                                        |
            |                                                        unsigned char *
      In file included from /usr/include/python3.11/Python.h:50,
                       from DisplayCAL/RealDisplaySizeMM.c:1:
      /usr/include/python3.11/bytesobject.h:34:50: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
         34 | PyAPI_FUNC(PyObject *) PyBytes_FromStringAndSize(const char *, Py_ssize_t);
            |                                                  ^~~~~~~~~~~~
      ['bdist_wheel', '--dist-dir', '/tmp/pip-wheel-2r46h4q_/.tmp-vycfzdzu']
      *** /usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py bdist_wheel --dist-dir /tmp/pip-wheel-2r46h4q_/.tmp-vycfzdzu
      using distutils
      desktopfile: /tmp/pip-install-4gevrkev/displaycal_49b12436ae5c447e85a2d64f79832215/DisplayCAL/../misc/displaycal.desktop
      desktopfile: /tmp/pip-install-4gevrkev/displaycal_49b12436ae5c447e85a2d64f79832215/DisplayCAL/../misc/displaycal-3dlut-maker.desktop
      desktopfile: /tmp/pip-install-4gevrkev/displaycal_49b12436ae5c447e85a2d64f79832215/DisplayCAL/../misc/displaycal-apply-profiles.desktop
      desktopfile: /tmp/pip-install-4gevrkev/displaycal_49b12436ae5c447e85a2d64f79832215/DisplayCAL/../misc/displaycal-curve-viewer.desktop
      desktopfile: /tmp/pip-install-4gevrkev/displaycal_49b12436ae5c447e85a2d64f79832215/DisplayCAL/../misc/displaycal-profile-info.desktop
      desktopfile: /tmp/pip-install-4gevrkev/displaycal_49b12436ae5c447e85a2d64f79832215/DisplayCAL/../misc/displaycal-scripting-client.desktop
      desktopfile: /tmp/pip-install-4gevrkev/displaycal_49b12436ae5c447e85a2d64f79832215/DisplayCAL/../misc/displaycal-synthprofile.desktop
      desktopfile: /tmp/pip-install-4gevrkev/displaycal_49b12436ae5c447e85a2d64f79832215/DisplayCAL/../misc/displaycal-testchart-editor.desktop
      desktopfile: /tmp/pip-install-4gevrkev/displaycal_49b12436ae5c447e85a2d64f79832215/DisplayCAL/../misc/displaycal-vrml-to-x3d-converter.desktop
      error: can't copy '/tmp/pip-install-4gevrkev/displaycal_49b12436ae5c447e85a2d64f79832215/DisplayCAL/../dist/net.displaycal.DisplayCAL.appdata.xml': doesn't exist or not a regular file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for displaycal
Failed to build displaycal
ERROR: Could not build wheels for displaycal, which is required to install pyproject.toml-based projects`

When it says "dependencies satisfied" .... it followed the installation of about 100 mega of dev packages for x11, Python and god knows what else. This is not an installation for a general user - I got this far because (a) I need it and (b) I'm a persistent idiot, not because I understand what's going on. When can we expect packages that work?

**Comment by p5k369** [comment] 2023-06-27 17:32
Hey @mabachel you are missing python-develop package
@brunkenj, @OldNick and @eoyilmaz indeed, it looks like there is some issue with the package that can be installed via pip directly from pypi, I could verify that with my local machine and 2 virtual machines all running different distributions.
That said, it was no problem to download the tarball from pypi untar it and install displaycal via pip locally.
I think that is a good workaround for now without much hassle.

> When it says "dependencies satisfied" .... it followed the installation of about 100 mega of dev packages for x11, Python and god knows what else. This is not an installation for a general user - I got this far because (a) I need it and (b) I'm a persistent idiot, not because I understand what's going on. When can we expect packages that work?

I'm not sure if I understand you correctly but if you are looking for precompiled packages for your system, you won't find them here, also not anytime in the future.

**Comment by OldNick** [comment] 2023-06-27 21:16
Hi, thanks for your reply.
I've Just tried your solution (ie pip without the sudo) and it fails with the same output in Konsole.

I wonder if later versions of Python impose stricter rules (Tumbleweed seems to go for the tightest version of anything)

**Comment by p5k369** [comment] 2023-06-27 22:12
Hey @OldNick,
just create a venv, download and extract the tarball and run pip install inside your extracted directory. 

It's just an advise frome me, so you are free to ignore it, but I would suggest to never ever run pip on system level, if everything works afterwards, it's just luck.

**Comment by OldNick** [comment] 2023-06-27 22:23
What is a venv?
As I said, my understanding of Python is Zero...

**Comment by p5k369** [comment] 2023-06-27 22:43
ok, so assuming you're on bash:

`wget https://github.com/eoyilmaz/displaycal-py3/releases/download/3.9.11/DisplayCAL-3.9.11.tar.gz`

`tar -xf DisplayCAL-3.9.11.tar.gz`

`python -m venv venv`

`source venv/bin/activate`

`cd DisplayCAL-3.9.11`

`pip install .`

you should be able to run displaycal by entering `displaycal`
If you want to call it, for example after a restart, remember to activate your created virtual environment before launch:

`source venv/bin/activate`

`displaycal`

**Comment by p5k369** [comment] 2023-06-27 22:53
> What is a venv?

12.1 the introduction to venv of the python tutorial which are only a couple sentences will bring you up to speed.
https://docs.python.org/3/tutorial/venv.html#introduction

The most important part here is:
>This means it may not be possible for one Python installation to meet the requirements of every application. If application A needs version 1.0 of a particular module but application B needs version 2.0, then the requirements are in conflict and installing either version 1.0 or 2.0 will leave one application unable to run.

**Comment by tgurr** [comment] 2023-06-28 14:23
Same on Exherbo obviously, the DisplayCAL-3.9.11 Source Distribution tarball from PyPI is missing said file `dist/net.displaycal.DisplayCAL.appdata.xml` which is/was present in the DisplayCAL-3.9.10 Source Distribution tarball.

![image](https://github.com/eoyilmaz/displaycal-py3/assets/414984/3ececb2d-35b5-4162-9983-d1abfe3dec3e)


Probably something went wrong in the release process? Please provide an updated/fixed Source Distribution tarball on PyPI.

**Comment by OldNick** [comment] 2023-06-28 20:39
I tried to follow your instructions...
Linux actually requires the installation of the "virtualenv" package and the command is "virtualenv <directory>" after that things go as you said (except that I had to "pip install build")...
However build failed with the message `FileNotFoundError: [Errno 2] No such file or directory: '/home/webby/DisplayCAL-3.9.11/misc/debian.rules'`

From @tgurr's comment above, it would seem that something has gone wrong with compiling the tarball...

**Comment by p5k369** [comment] 2023-06-28 21:06
@OldNick it doesnt matter if that file is found, and you did not `pip install .` . Try it.
There are 2 workarounds, either you generate it (that is what we are doing) or you comment out the part in setup.py that tries to copy the not available file (that is what @tgurr is doing).

**Comment by OldNick** [comment] 2023-06-28 21:29
Tried "pip install" and in the file is the result. It failed. I then went on to try and install something that's already in the system - so long that I couldn't get all the text from Konsole. Doing things under virtalenv is _very_ verbose.

Frankly this is becoming a bloody nightmare.

3.9 installed and worked beautifully (even if I was cursing to get all the dependencies). I lost it because a system update bricked the computer. I have a feeling that, although python claims to be cross platform, it is heavily weighted towards Windows with Linux as a secondary consideration.

[dISPLAcAL-ERROR.TXT](https://github.com/eoyilmaz/displaycal-py3/files/11900047/dISPLAcAL-ERROR.TXT)

**Comment by p5k369** [comment] 2023-06-28 21:45
Hey @OldNick, you made it, now it's only a dependeny thing, but you would have experienced that even with a working package from Pypi.
From the log it looks like you're missing the _dbus-1-dev_ package (and probably _libX11-devel_ also). I don't know if that is how they are called in opensuse. 

> Frankly this is becoming a bloody nightmare.

From my perspective this looks pretty normal for someone with not so much experience in python. You're on the way, (as I said, now it's only about installing the dependencies) don't let yourself down.

> I have a feeling that, although python claims to be cross platform, it is heavily weighted towards Windows with Linux as a secondary consideration.

As someone whos doing cross platform development I can say that's not the case and in fact personally I find dealing with the environment and so on is easier on linux than on windows.

**Comment by OldNick** [comment] 2023-06-28 22:08
All the packages are there - and a lot of them since the beginning. 
The comment at the end of the file (which surprised me because it's in decent English) says it doesn't understand why pip is trying to install a new instance of dbus when there are already 5 available!

The problem is pip, or rather with some of its packages which seem to ask for the impossible. I just want to be able to calibrate my monitor without spending hours dealing with something I'm not interested in.

**Comment by p5k369** [comment] 2023-06-28 22:15
@OldNick as I already wrote you're missing _dbus-1-dev_  or maybe it's called _dbus-1-devel_ in opensuse

>All the packages are there - and a lot of them since the beginning.

I doubt that.

**Comment by brunkenj** [comment] 2023-06-29 13:09
@p5k369 - I cloned the repo and did a manual install, and it built without any problems. I ran dnf install, prior to starting the build, to find out if any of the dependencies were missing. All of them were there. 

Will there be a release that fixes this issue?

**Comment by eoyilmaz** [comment] 2023-07-01 11:43
@brunkenj currently we don't offer any package specific for a particular Linux distro. That means you need to install the prerequsities (that are not Python packages and doesn't exist in PIP) by yourself and we have tutorials for that in the main project page. So anything that is not PIP related, we'll not have a fix in the shortrun.

**Comment by brunkenj** [comment] 2023-07-02 12:19
My question was, will there be a fix that addresses *this* isue. Issue 264.

**Comment by OldNick** [comment] 2023-07-09 16:17
It would have been more useful and saved me a lot of time and energy to be told there is a Flatpak available...

**Comment by p5k369** [comment] 2023-07-09 18:23
Hi @OldNick, the issue is called "pip install of 3.9.11 failed on Fedora 38 with Python 3.11" from the displaycal-py3 repository. I can't see that this is in any way related to the third party displaycal flatpack package or could be fixed by using it.

**Comment by OldNick** [comment] 2023-07-10 19:16
It's a bit disingenuous to characterize the flatpak as 3rd party - I note that a file was included in the latest version explicitly to enable building the flatpak.

You could perhaps have suggested using it as a workaround while you sort out getting the pip version working... had I known about it I wouldn't have wasted so much time - mine and yours

As it is the flatpak works without a problem - I recalibrated my monitor this morning.

**Comment by p5k369** [comment] 2023-07-10 20:32
Hey @OldNick I think you did not get the point, don't get me wrong I'm in for discussions about various ways of installing displaycal, so feel free to open a discussion here: https://github.com/eoyilmaz/displaycal-py3/discussions 
And if that's what you want, I'd ask you to do it too.
This issue and your preferred way of getting displaycal running on your machine is not related.

> It's a bit disingenuous to characterize the flatpak as 3rd party - I note that a file was included in the latest version explicitly to enable building the flatpak

No, its exactly that and all credits go to the creater of the displaycal-flatpak repository. The single line of code you are reffering to is the content rating which was included. That is not flatpak specific at all and also not really a change of the codebase.

> You could perhaps have suggested using it as a workaround while you sort out getting the pip version working

The version you tried to install in your virtual environment is working, you simply refused to install the required development dependencies. You obviously got confused more than once. This is only because of your lack of knowledge about how your system and the python ecosystem works (and that is no dealbreaker you just have to keep going), belive me or not, but everything you did brought you one step closer. 

> As it is the flatpak works without a problem 

Getting rid of opensuse and using a different linux distribution that provides native packages for displaycal would also work without problems but it does not contribute anything to fix the issue: "pip install of 3.9.11 fails on Fedora 38 with Python 3.11"

**Comment by eli-schwartz** [comment] 2023-07-19 01:32
The discussion about getting pip install to work misses the point that there's a whole bunch of files which *cannot* be in a virtualenv. In particular, virtualenvs only support:
- bin programs (entry points or scripts)
- importable modules in the python site-packages

Things you cannot do:
- install to /etc/xdg
- install icon themes
- install documentation
- install appstream data (appdata.xml)
- install udev rules
- install desktop files

This isn't even virtualenv specific, though, it's about pip and wheels and the nature of python packaging. Specifically, the python packaging ecosystem has decided to get out of the game of providing application packaging, and sticking to "python modules that you can run with a script entry point" packaging. System integration, in particular, is too complex to capture in the wheel model and they don't intend to focus on it.

If you forego use of pip and forego the creation of wheels, and require users to run `python3 setup.py install`, you can manually install to absolute paths by using setup.py as a kind of Makefile. In the long run, setuptools has already deprecated and plans to remove the ability to do that. They consider wheels to be the only supported approach.

For application packaging, python packaging simply isn't a good fit. But there are alternatives.

Question: how important is it to support a "degraded mode" installation that just installs a runnable script+module without any support files?

**Comment by eoyilmaz** [comment] 2024-03-19 01:21
Closing this because of inactivity... Open it back if required.

**Closed by eoyilmaz** 2024-03-19 01:21 UTC
