### ISSUE TITLE
generated 3D LUT for ReShade is broken

### ISSUE THREAD

**Issue by aufkrawall** [eoyilmaz/displaycal-py3#118] opened 2022-05-19 13:47 UTC
Image viewers just display black content when opening the PNG file and vkbasalt crashes when it tries to use this file. It worked with last 3.8.x. version.
Tried with rec709 rel. gamma 2.4 and "apply calibration" checkbox unticked and DisplayCal 3.9.4.

**Comment by eoyilmaz** [comment] 2022-05-19 17:02
I have no idea about what are you talking about!!!

> Image viewers just display black content

What image viewer?

> vkbasalt crashes

What is vkbasalt?

> Tried with rec709 rel. gamma 2.4 and "apply calibration" checkbox unticked and DisplayCal 3.9.4.

what's that? In what editor are you, share screen shots, error messages (from DisplayCAL) and other useful steps to reproduce your problem.

**Comment by eoyilmaz** [comment] 2022-06-04 23:48
My guess is that you are using DisplayCAL 3DLUT Maker and the resultant LUT file (which format?) is causing you problems with some image viewer applications.

I've generated LUTs to be used with BlackMagic Fusion for my own work and they were working properly without any issues at all. To be honest, unless you supply your ICC profile, the generated LUT file and the steps to reproduce the error, I can't do much about this error report. And 16 days passed already without an answer from you. So, this issue might get closed because of inactivity from the original reporter.

**Comment by aufkrawall** [comment] 2022-06-05 01:53
Sorry for the delay, I'll be providing an example ICC profile and generated 3D LUTs (PNGs) soon.

**Comment by aufkrawall** [comment] 2022-06-05 13:46
Used ICC profile:
[G27q-20 #1 2022-05-25 22-12 D6500 2.4 M-S XYZLUT+MTX.zip](https://github.com/eoyilmaz/displaycal-py3/files/8840065/G27q-20.1.2022-05-25.22-12.D6500.2.4.M-S.XYZLUT%2BMTX.zip)

Used settings:
![Screenshot_20220605_151913](https://user-images.githubusercontent.com/13510490/172053632-51903509-6b62-4ee3-99d6-ffc35e1e068c.png)


3D LUT 3.9.3 (image viewers can't decode it, apparently Firefox neither):
![3 9 4](https://user-images.githubusercontent.com/13510490/172053640-f26fea5d-e6d0-4e70-9f5d-f85a52e39183.png)

Correct result with 3.8.9.3:
![3 8 9 3](https://user-images.githubusercontent.com/13510490/172053651-3facc438-97b7-4621-87ca-e02f91b9ddb4.png)

This is on Arch btw. Not sure if the packaging situation with Python dependencies is optimal with that Linux distribution. The DisplayCal 3.9.3 package they ship doesn't even start without aborting with an error message on some of my systems, I'm going to report that to them.

**Comment by eoyilmaz** [comment] 2022-06-05 14:59
Aah okay, that's cool, thank you. This is probably related with our PNG code.

**Comment by eoyilmaz** [comment] 2022-06-05 15:05
> This is on Arch btw. Not sure if the packaging situation with Python dependencies is optimal with that Linux distribution. The DisplayCal 3.9.3 package they ship doesn't even start without aborting with an error message on some of my systems, I'm going to report that to them.

Don't bother, the packages is here, he has created an issue with our installation routines, we are working on that :+1:

**Comment by eoyilmaz** [comment] 2022-06-05 16:47
Okay, this is fixed with 77f7401
Thank you for reporting :+1:

**Closed by eoyilmaz** 2022-06-05 16:47 UTC
Labels: waiting user data
