### ISSUE TITLE
Just doesn't run on M1/M2

### ISSUE THREAD

**Issue by writedirect** [eoyilmaz/displaycal-py3#299] opened 2023-10-19 19:24 UTC
I LOVE the fact that DisplayCAL has been picked up. But after installing BREW and DisplayCAL ran into a show stopper: It will not download the latest ArgyllCMS files. Now sure, you can go grab them and then tell DisplayCAL where to look for them, but this is an OSX nightmare, because it will throw a million warnings trying to run the app.

I gave up and went back to the old package installer for DisplayCAL off the website. It downloads the latest ArgyllCMS without issue (3.0.1). So I'm not sure why I need to try and move to this new package?

Again, love that someone is continuing the dev work. I'd pay for this as an app in a heart beat.

**Comment by rjeffman** [comment] 2023-10-20 14:42
It seems to be a duplicate of #298

**Comment by MStraeten** [comment] 2023-10-22 11:34
by default theres a `dl` directory in `~/Library/Application\ Support/DisplayCAL`
if you copy the unpacked Argyll_V3.0.1 directory there, you can manually select the binary folder.
but since the Argyll-stuff isn't codesigned you need to 'help' gatekeeper to be fine with it:
run `xattr -c ~/Library/Application\ Support/DisplayCAL/dl/Argyll_V3.0.1/bin/*` from terminal before selecting the folder ...

**Comment by eoyilmaz** [comment] 2024-03-10 23:31
This issue title is a little vague. The application runs under M1/M2 (at least I can run it under my M1 Pro and theoratically there should be no difference to run it under M2). The complain about "not being easy to run the ArgyllCMS executables" is acceptable. But, then the issue title should be changed, and probably it is better to drop it to ArgyllCMS: https://www.argyllcms.com/mailinglist.html

And "cannot download ArgyllCMS executables through the menus" is a better title for this issue, and then as @rjeffman pointed out this is a duplicate of #298 

Thus, closing this...

**Closed by eoyilmaz** 2024-03-10 23:31 UTC
