### ISSUE TITLE
TypeError: can't concat int to bytes

### ISSUE THREAD

**Issue by reindeerphotode** [eoyilmaz/displaycal-py3#40] opened 2022-03-18 15:25 UTC
Dear Erkan,

after a full "Calibrate & profile" run I got the following error messages:

TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/wx/lib/delayedresult.py", line 267, in wrapper
    result = workerFn(*args, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 1838, in __call__
    result = self.producer(*args, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 11569, in create_profile
    result = self.update_profile(
  File "/usr/local/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 12182, in update_profile
    b"\0\0" + edid["edid"][9] + edid["edid"][8]
TypeError: can't concat int to bytes

Used setup:
Spyder5 (datacolor)
Opensuse Tumbleweed ()
python 3.8

I am not sure where this cast integer to byte happens...
I have no idea whether this helps...

From the user point of view:
Thank you very much. I was a long time not that close to get a decent monitor calibration. 

Best regards 

   Marc

P.S. can someone give me a hint why the TypeError stuff is written with **bold** letters?

**Comment by eoyilmaz** [comment] 2022-03-19 09:21
Hey @reindeerphotode thanks for the bug report, what you have supplied is enough to fix this error, I'll deal with that today :+1:

**Comment by eoyilmaz** [comment] 2022-03-19 19:16
This should be fixed now, can you please test it.

**Closed** 2022-03-19 19:15 UTC

**Comment by eoyilmaz** [comment] 2022-03-19 19:20
By the way you may need to delete the ``$HOME/.config/DisplayCAL`` folder, which may contain wrong values.

**Comment by reindeerphotode** [comment] 2022-03-20 09:44
Dear Erkan,

I did a full rebuild and removed  `$HOME/.config/DisplayCAL` completely.

Result: Another CAST Problem: string to byte or vice versa.

DisplaCAL did an output on a window:
![Screenshot_20220320_104055_DisplayCAL](https://user-images.githubusercontent.com/101870638/159156715-1ec72a43-a753-4863-8516-537e73103da1.png)


Error output on the terminal:
`TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
--------------------------------------------------------------------------------
/usr/lib64/python3.8/site-packages/DisplayCAL/colord.py:182: Warning: CDError("gi.repository.GLib.Error: GLib.Error('GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ColorManager was not provided by any .service files', 'g-dbus-error-quark', 2)")
  warnings.warn(safe_str(exception), Warning)
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/wx/lib/delayedresult.py", line 267, in wrapper
    result = workerFn(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 1838, in __call__
    result = self.producer(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 11572, in create_profile
    result = self.update_profile(
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 12329, in update_profile
    profile.calculateID()
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 6645, in calculateID
    data = self.data
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 8041, in __getattribute__
    return object.__getattribute__(self, name)
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 6445, in data
    tagData = self.tags[tagSignature].tagData
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 4653, in tagData
    tagData.append(uInt32Number_tohex(size))
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 2871, in uInt32Number_tohex
    return struct.pack(">I", int(round(num)))
struct.error: 'I' format requires 0 <= number <= 4294967295

DisplayCAL: Uninhibited org.freedesktop.ScreenSaver
DisplayCAL: Uninhibited org.freedesktop.PowerManagement.Inhibit
`
Best regards

   Marc

**Comment by eoyilmaz** [comment] 2022-03-20 16:07
Moved this to a new issue. For future reference, it is better for me if you report a new issue if it is not related to the previous issue.

**Comment by eoyilmaz** [comment] 2022-03-20 16:35
I can't reproduce this error. Can you send over the generated ICC profile under ``$HOME/.local/share/DisplayCAL/storage/{ICC_Profile_Name}/{ICC_Profile_Name}.icc``
