### ISSUE TITLE
MacOS Sonoma (DisplayCal Python) + Blackmagic UltraStudio (DaVinci Resolve)

### ISSUE THREAD

**Issue by BastienChilloux** [eoyilmaz/displaycal-py3#308] opened 2023-12-10 10:38 UTC
Hi,

As you know, the native MacOS app doesn’t work since MacOS Sonoma has been released.
So I tried using your Python 3 version.

As far as the DisplayCal Python works properly with external monitor, it doesn’t work within Resolve with the UltraStudio I/O device.

It doesn’t work when using DaVinci Resolve with an i/o device, such as the Blackmagic UltraStudio Mini 4K : the color patches are not sent to the i/o device, so not displayed on the monitor plugged into it. The IP connection is working fine though. The calibration fails at the very first steps. I only see a grey patch and then the measurements give an error.

Do you have any clue if this is something you could fix or implement in the near future for the version of DisplayCal that you have ported to Python 3?

This topic is also discussed here: https://hub.displaycal.net/forums/topic/macos-sonoma-displaycal-python-blackmagic-ultrasutdio-davinci-resolve/#post-140006

Thank you

**Comment by eoyilmaz** [comment] 2024-03-10 17:52
This is a duplicate of #302 closing this, please follow that issue ticket for any updates.

**Closed by eoyilmaz** 2024-03-10 17:52 UTC
Labels: duplicate
