### ISSUE TITLE
crash when quitting on macOS Sonoma 14.6

### ISSUE THREAD

**Issue by raylau1234** [eoyilmaz/displaycal-py3#388] opened 2024-08-01 00:54 UTC
**Describe the bug**
When quitting, crashes with

```
Exception ignored in: <function Player.__del__ at 0x1188a7060>
Traceback (most recent call last):
  File "/Users/REDACTED/Documents/scripts/git/displaycal-py3/.venv/lib/python3.12/site-packages/pyglet/media/player.py", line 138, in __del__
  File "/Users/REDACTED/Documents/scripts/git/displaycal-py3/.venv/lib/python3.12/site-packages/pyglet/media/player.py", line 249, in delete
  File "/Users/REDACTED/Documents/scripts/git/displaycal-py3/.venv/lib/python3.12/site-packages/pyglet/media/drivers/openal/adaptation.py", line 128, in delete
  File "/Users/REDACTED/Documents/scripts/git/displaycal-py3/.venv/lib/python3.12/site-packages/pyglet/media/drivers/openal/interface.py", line 159, in delete
TypeError: 'NoneType' object is not callable
bash: line 1: 36788 Segmentation fault: 11  displaycal
make: *** [launch] Error 139
```

**To Reproduce**
1. `make launch` to launch display cal
2. quit

**Expected behavior**
Quitting should not crash

**Versions (please complete the following information):**
 - OS: macOS Sonoma 14.6
 - Python Version 3.12.4
 - ArgyllCMS Version 3.2.0
 - DisplayCAL Version 3.9.12 but specifically head of `develop` at the time of this report (eda424388be5dc18f76b02f8d015d6b2ddafa174)

**Additional context**
Pretty harmless as it's on quit, but thought I would report anyway

**Comment by p5k369** [comment] 2024-08-02 19:35
duplicate of #341

**Comment by p5k369** [comment] 2024-08-13 20:59
Closing this one.
It is a duplicate of a known issue.

**Closed by p5k369** 2024-08-13 20:59 UTC
Labels: duplicate

**Comment by eoyilmaz** [comment] 2026-03-03 21:59
This was not related to #341 re-opening it.
