### ISSUE TITLE
Bad request when attempting to update ArgyllCMS

### ISSUE THREAD

**Issue by writedirect** [eoyilmaz/displaycal-py3#298] opened 2023-10-19 18:22 UTC
Hey! Have DislplayCAL installed on M1 Mac. Python 3.11 and the app opens and prompts about the ArgyllCMS update. But when I tell it to update, it throws and error. Thanks!

**Comment by rjeffman** [comment] 2023-10-20 14:43
Can you paste the terminal output so I can take a look?

**Comment by writedirect** [comment] 2023-10-20 19:15
Hey man...thanks so much for responding. Here's the deal -- I REALLY LOVE what you guys are doing with keeping DisplayCAL alive. However for my students it's too complicated at the moment. I can install the 2019 version on an M1 Mac, get the latest ArgyllCMS with the of a click of a button and not have to get students deep in the weeds with Brew, etc. If this continues to evolve, I'm all about diving in again. This thread can be closed. Thanks so much!

**Comment by MStraeten** [comment] 2023-10-22 11:26
terminal output:
```
myuser@MBP-von-Martin ~ % /Users/myuser/displaycal_venv/bin/displaycal ; exit;
Acquired lock file: <DisplayCAL.main.AppLock object at 0x100115210>
displaycal 3.9.11 2023-10-08T09:46:05Z
Mac OS X 14.0 arm64
Python 3.11.6 (main, Oct  7 2023, 23:11:05) [Clang 15.0.0 (clang-1500.0.40.1)]
CA file /Users/myuser/displaycal_venv/lib/python3.11/site-packages/certifi/cacert.pem
Faulthandler 
wxPython 4.2.1 osx-cocoa (phoenix) wxWidgets 3.2.2.1
Encoding: utf-8
File system encoding: utf-8
Loading /Users/myuser/Library/Preferences/DisplayCAL/DisplayCAL.ini
listening
writing to lock file: port: 15411
Starte...
2023-10-22 13:23:07.200 Python[62595:1702979] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
SDL2: /opt/local/lib/libSDL2.dylib
SDL2_mixer: None
Audio-Modul: wx 4.2.1
Anzeigegeräte- und Messgeräte-Erkennung...
/Users/myuser/Library/Application Support/DisplayCAL/dl/Argyll_V2.3.1/bin
ArgyllCMS 2.3.1
Argyll has virtual display support
...ok.
Initialisiere GUI...

instrument_name: i1 DisplayPro, ColorMunki Display
display_name   : Built-in Retina Display
...ok.
Bereit.
Starte Skript-Host unter 127.0.0.1:15411
Auf Programmaktualisierung überprüfen...
DisplayCAL ist auf dem neuesten Stand.
┌──────────────────────────────────────────────────────────────────────────────┐
│ Es ist eine Programmaktualisierung verfügbar: ArgyllCMS 3.0.1                │
└──────────────────────────────────────────────────────────────────────────────┘
-> Jetzt aktualisieren
Using CA file /Users/myuser/displaycal_venv/lib/python3.11/site-packages/certifi/cacert.pem
Verbinde mit https://displaycal.net:443...
┌──────────────────────────────────────────────────────────────────────────────┐
│ HTTP Error 400: Bad Request                                                  │
└──────────────────────────────────────────────────────────────────────────────┘

```
option "go to website" opens  https://www.argyllcms.com/downloadmac.html instead

**Comment by ilveroluca** [comment] 2023-10-25 08:33
I can confirm this issue. Just tried with version 3.9.11 installed in a dedicated venv, on (K)ubuntu 22.04.

```
displaycal-py3] displaycal
Acquired lock file: <DisplayCAL.main.AppLock object at 0x7f2ccbcead70>
displaycal 3.9.11 2023-10-25T08:26:30Z
ubuntu 22.04 jammy x86_64
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Faulthandler 
wxPython 4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1
...
```

**Comment by ealmbrat** [comment] 2024-01-05 09:16
+1 Can't download AgryllCMS. Results in "HTTP Error 400: Bad Request".

Displaycal-py3 3.9.11. Ubuntu 20.04.6 LTS. On a x86 Intel CPU.

**Comment by luator** [comment] 2024-02-11 11:11
Same issue here.  I saw that it was already reported in #291, though, so I suggest to close this one as duplicate.

**Comment by eoyilmaz** [comment] 2024-03-10 23:33
closing this as it is suggested being duplicate of #291

**Closed by eoyilmaz** 2024-03-10 23:33 UTC
