### ISSUE TITLE
Build problem pip install (opensuse tumbleweed) 

### ISSUE THREAD

**Issue by reindeerphotode** [eoyilmaz/displaycal-py3#98] opened 2022-05-02 11:07 UTC
Dear Erkan,

I tested the ne build an setup path.

pip install -r requirements.txt

gave:
      [  1/921] Compiling sip/siplib/qtlib.c
      [  2/921] Compiling sip/siplib/bool.cpp
      [  3/921] Compiling sip/siplib/apiversions.c
      [  4/921] Compiling sip/siplib/objmap.c
      [  5/921] Compiling sip/siplib/voidptr.c
      [  6/921] Compiling sip/siplib/int_convertors.c
      [  7/921] Compiling sip/siplib/array.c
      [  8/921] Compiling sip/siplib/threads.c
      [  9/921] Compiling sip/siplib/descriptors.c
      [ 10/921] Compiling sip/siplib/siplib.c
      [ 11/921] Compiling sip/cpp/sip_corewxLogTextCtrl.cpp
      In file included from ../../../../ext/wxWidgets/include/wx/defs.h:45,
                       from ../../../../ext/wxWidgets/include/wx/wx.h:14,
                       from ../../../../wx/include/wxPython/wxpy_api.h:41,
                       from ../../../../sip/cpp/sipAPI_core.h:20845,
                       from ../../../../sip/cpp/sip_corewxLogTextCtrl.cpp:10:
      ../../../../ext/wxWidgets/include/wx/platform.h:159:10: fatal error: wx/setup.h: No such file or directory
        159 | #include "wx/setup.h"
            |          ^~~~~~~~~~~~
      compilation terminated.
      
      Waf: Leaving directory `/tmp/pip-install-iifnhpk7/wxpython_7b1e73c7a42a4bdaa6d60b32fcb395ef/build/waf/3.8/gtk3'
      Build failed
       -> task in '_core' failed with exit status 1 (run with -v to display more information)
      Command '"/home/marc/python/displaycal_venv/bin/python3" /tmp/pip-install-iifnhpk7/wxpython_7b1e73c7a42a4bdaa6d60b32fcb395ef/bin/waf-2.0.19 --wx_config=/tmp/pip-install-iifnhpk7/wxpython_7b1e73c7a42a4bdaa6d60b32fcb395ef/build/wxbld/gtk3/wx-config --gtk3 --python="/home/marc/python/displaycal_venv/bin/python3" --out=build/waf/3.8/gtk3 configure build ' failed with exit code 1.
      Finished command: build_py (0m4.378s)
      Finished command: build (2m30.782s)
      Command '"/home/marc/python/displaycal_venv/bin/python3" -u build.py build' failed with exit code 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxPython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by eoyilmaz** [comment] 2022-05-04 18:18
This is a duplicate of #66

**Closed by eoyilmaz** 2022-05-04 18:18 UTC
Labels: duplicate
