### ISSUE TITLE
All ΔE values = 0 during testchart

### ISSUE THREAD

**Issue by umtiagopereira** [eoyilmaz/displaycal-py3#295] opened 2023-10-06 15:56 UTC
All the dE values of the verification testchart report are equal to 0. This seems to be an issue that just happens with this python3 version of displaycal.

![CleanShot 2023-10-06 at 12 55 09](https://github.com/eoyilmaz/displaycal-py3/assets/145727709/6205cb73-b250-4855-9131-72f67c35c02d)

**Comment by MUWalter** [comment] 2023-11-30 17:43
Yes, I have the same bug. How can it be fixed?

**Comment by quietvoid** [comment] 2024-01-09 19:40
This seems to be a duplicate of #276 which is supposed to be fixed but there hasn't been a new release yet.
I'll try running a verification on the latest develop commit later to try.

**Comment by quietvoid** [comment] 2024-01-09 22:40
Right, on the `develop` branch this issue is fixed for me.

**Comment by MUWalter** [comment] 2024-01-15 10:11
I am also on the latest develop branch and this issue isn't fixed for me.

**Comment by eoyilmaz** [comment] 2024-03-10 01:17
I cannot reproduce this on my Macbook Pro with M1 Pro:

![image](https://github.com/eoyilmaz/displaycal-py3/assets/1786804/7f782cd0-3ee6-4d01-8401-46ca94c16488)

I'll release 3.9.12 soon, please test it again afterwards...

**Comment by eoyilmaz** [comment] 2024-03-10 01:19
I'll close this, please open it again if you think it is not working for you.

**Comment by MUWalter** [comment] 2024-03-18 14:21
I am still getting only 0 as values. I just installed the latest version.

**Comment by eoyilmaz** [comment] 2024-03-19 22:44
3.9.12 is released. Can you please try it.

**Comment by MUWalter** [comment] 2024-03-22 09:31
> 3.9.12 is released. Can you please try it.

Works like a charm. Although I have to admit that I didn't know that you had to delete everything before so Displaycal gets an actual update. I guess I was still using 3.9.11 standard version. Anyway, following the instructions, I got an error message (both ways) installing it, as displaycal doesn't seem to open when python 3.12 is installed. Unfortunately phyton 3.12 gets installed when doing it according to the instructions. My workaround was to download version 3.11 dmg and install the package: https://www.python.org/downloads/release/python-3118/

But great works, now everything I need works for me! Thank you very much for all the effort you put into this!
All the best,
Mark

**Comment by eoyilmaz** [comment] 2024-03-22 09:33
Glad to hear that it is okay now, closing this 👍

**Closed by eoyilmaz** 2024-03-22 09:33 UTC
