### ISSUE TITLE
DisplayCAL 3.9.14 for Windows dispread.exe could not be started.

### ISSUE THREAD

**Issue by FQDianYan** [eoyilmaz/displaycal-py3#453] opened 2024-10-25 15:10 UTC
**Describe the bug**
DisplayCAL 3.9.14 for Windows dispread.exe could not be started.

**To Reproduce**
1. Calibrate & profile
2. Start measurement
3. See error

**Screenshots**
![屏幕截图 2024-10-25 230418](https://github.com/user-attachments/assets/f89959b4-a93b-477f-bd2e-13c98aadb09d)

**Versions (please complete the following information):**
 - OS: Windows 11 24H2 10.0.26100.2033 x86_64
 - Python Version: 3.11
 - ArgyllCMS Version: 3.3.0
 - DisplayCAL Version: 3.9.14

**Additional context**

**Comment by Headcrabed** [comment] 2024-10-25 17:35
Hello, where did you install displaycal from? pip or installer?

**Comment by FQDianYan** [comment] 2024-10-25 17:42
I'm install displaycal from installer.

**Comment by Admittedly-Goat** [comment] 2024-10-28 13:35
I've met the same issue today. After looking at the log file located at `C:\Users\[MY USER NAME]\AppData\Roaming\DisplayCAL\logs\wexpect.log`, I've found the following line indicating some potential problems:

```
2024-10-28 19:44:11,827 "C:\DisplayCAL\lib\python.exe" -S -c "import sys;setattr(sys, 'frozen', '%s'); sys.path = ['C:\\DisplayCAL', 'C:\\DisplayCAL\\library.zip', 'C:\\DisplayCAL\\library.zip\\DisplayCAL', 'C:\\DisplayCAL\\lib\\library.zip', 'C:\\DisplayCAL\\lib\\library.zip\\DisplayCAL'] + sys.path;args = ['C:\\Users\\Admin\\AppData\\Roaming\\DisplayCAL\\dl\\Argyll_V3.3.0\\bin\\dispread.exe', '-v', '-k', 'C:\\DisplayCAL\\linear.cal', '0_16']; from DisplayCAL import wexpect;wexpect.ConsoleReader(wexpect.join_args(args), 18104, 6140, cp=936, c=160, r=None, logdir='DisplayCAL')"
2024-10-28 19:44:31,837 Timeout exceeded in Wtty.spawn().
```

When manually running the python shipped with DisplayCAL-py3, the following problem happened:

```
> "C:\DisplayCAL\lib\python.exe"

init_fs_encoding: failed to get the Python codec of the filesystem encoding
...
ModuleNotFoundError: No module named 'encodings'
```

I have another Windows computer that can run DisplayCAL-py3 without any major problem. I've compared the two computers and found that the potential difference is that, on the working computer, I have python 3.11 installed at C:\Python311 (installed using official installer), while the problematic computer doesn't have it. I've tried to install python 3.11 on the problematic computer (also at C:\Python311), and the problem is solved.

I personally think that the problem is about the python shipped with DisplayCAL-py3. I'm not quite familiar with how bundled python works, so I'm just providing the solution that worked for me.

The environment to reproduce the problem is quite simple: a clean install of Windows, and installing DisplayCAL-py3. I hope this can be helpful.

**Comment by VgerTest** [comment] 2024-10-31 19:06
Reported in #424 same issue, maybe you should close this one and moving to the other thread since it has its own branch

**Closed** 2024-11-01 02:25 UTC
